IS_Project-master/IS_Project-master/EShop.Web/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EShop.Domain.Domain;
using EShop.Repository;
using System.Security.Claims;
using EShop.Service.Interface;

namespace EShop.Web.Controllers
{
    public class BooksController : Controller
    {
        
        private readonly IBookService bookService;
        private readonly IAuthorService authorService;
        private readonly IShoppingCartService shoppingCartService;
       
        public BooksController(IBookService bookService, IShoppingCartService shoppingCartService,IAuthorService authorService)
        {
            this.shoppingCartService = shoppingCartService;
            this.bookService = bookService;
            this.authorService = authorService;
         
        }

        // GET: Books
        public IActionResult Index()
        {
           
            return View(bookService.GetBooks());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = bookService.GetBookById(id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            var authors =authorService.GetAuthors();
            ViewBag.Authors = new SelectList(authors, "Id", "FirstName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,yearOfRelease,BookImage,AuthorId,genre,,Price,IsAvailable,Id")] Book book)
        {
            if (ModelState.IsValid)
            {
                book.Id = Guid.NewGuid();
                bookService.CreateNewBook(book);
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }
        public IActionResult AddToCart(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = bookService.GetBookById(id);  

            BookInShoppingCart ps = new BookInShoppingCart();

            if (product != null)
            {
                ps.BookId = product.Id;
            }

            return View(ps);
        }

        [HttpPost]
        public IActionResult AddToCartConfirmed(BookInShoppingCart model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            shoppingCartService.AddToShoppingConfirmed(model, userId);
            return View("Index", bookService.GetBooks());
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = bookService.GetBookById(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Title,Description,yearOfRelease,AuthorId,genre,IsAvailable,Price,Id")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    bookService.UpdateBook(book);
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = bookService.GetBookById(id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            bookService.DeleteBook(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

IS_Project-master/IS_Project-master/EShop.Web/Controllers/PublishersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EShop.Domain.Domain;
using EShop.Repository;
using EShop.Service.Interface;
using EShop.Service.Implementation;

namespace EShop.Web.Controllers
{
    public class PublishersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPublishService publishService;

        public PublishersController(ApplicationDbContext context,IPublishService publishService)
        {
            _context = context;
            this.publishService = publishService;
        }

        // GET: Publishers
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Publishers.Include(p => p.Book);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Publishers/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publishers = await _context.Publishers
                .Include(p => p.Book)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publishers == null)
            {
                return NotFound();
            }

            return View(publishers);
        }

        // GET: Publishers/Create
        public IActionResult Create(Guid? Id)
        {
            if (Id == null)
            {
                return BadRequest("BookId is required.");
            }

            var book = _context.Books.Find(Id);
            if (book == null)
            {
                return NotFound("Book not found.");
            }

            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Title", Id);
            ViewData["AuthorsId"] = new SelectList(_context.Authors, "Id", "Name", book.AuthorId);

          
            var model = new Publishers
            {
                BookId = Id.Value,
                AuthorsId = book.AuthorId.Value
            };

            return View(model);
        }


        // POST: Publishers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookId,AuthorsId,PublishDate,OrderDate,RentAmount,Id")] Publishers publishers)
        {
            if (ModelState.IsValid)
            {
                publishers.Id = Guid.NewGuid();
                publishService.CreateNewPublish(publishers);
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "Title", publishers.BookId);
            ViewData["AuthorsId"] = new SelectList(_context.Authors, "Id", "Name", publishers.AuthorsId);
            return View(publishers);
        }

        // GET: Publishers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publishers = await _context.Publishers.FindAsync(id);
            if (publishers == null)
            {
                return NotFound();
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "AuthorId", publishers.BookId);
            return View(publishers);
        }

        // POST: Publishers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("BookId,AuthorsId,PublishDate,OrderDate,RentAmount,Id")] Publishers publishers)
        {
            if (id != publishers.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(publishers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PublishersExists(publishers.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookId"] = new SelectList(_context.Books, "Id", "AuthorId", publishers.BookId);
            return View(publishers);
        }

        // GET: Publishers/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = publishService.GetPublisherById((Guid)id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: Publishers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            publishService.DeletePublish(id);
            return RedirectToAction(nameof(Index));
        }

        private bool PublishersExists(Guid id)
        {
            return _context.Publishers.Any(e => e.Id == id);
        }
    }
}

IS_Project-master/IS_Project-master/EShop.Web/Views/Books/AddToCart.cshtml
@model EShop.Domain.Domain.BookInShoppingCart

<h1>Add product to Shopping cart</h1>

<div class="row">
    <div class="col-4">

        <form asp-action="AddToCartConfirmed">
            <input type="hidden" asp-for="BookId" />

            <div class="form-group">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Add To Cart" class="btn-info" />
            </div>
        </form>
    </div>
</div>

IS_Project-master/IS_Project-master/EShop.Web/Views/Books/Create.cshtml
@model EShop.Domain.Domain.Book

@{
    ViewData["Title"] = "Create";
}

<div class="container mt-4">
    <h1 class="mb-4">@ViewData["Title"]</h1>

    <div class="card shadow-lg">
        <div class="card-header bg-primary text-white">
            <h4>Create New Book</h4>
        </div>
        <div class="card-body">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>

                <div class="mb-3">
                    <label asp-for="Title" class="form-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Description" class="form-label"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="yearOfRelease" class="form-label"></label>
                    <input asp-for="yearOfRelease" class="form-control" />
                    <span asp-validation-for="yearOfRelease" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="BookImage" class="form-label"></label>
                    <input asp-for="BookImage" class="form-control" />
                    <span asp-validation-for="BookImage" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label>Select Author</label>
                    @Html.DropDownListFor(x => x.AuthorId, ViewBag.Authors as SelectList, "Select Author", new { @class = "form-control" })
                    <span asp-validation-for="AuthorId" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="genre" class="form-label"></label>
                    <input asp-for="genre" class="form-control" />
                    <span asp-validation-for="genre" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Price" class="form-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="IsAvailable" class="form-label"></label>
                    <input asp-for="IsAvailable" class="form-control" />
                    <span asp-validation-for="IsAvailable" class="text-danger"></span>
                </div>

                <div class="d-grid mt-4">
                    <button type="submit" class="btn btn-primary btn-block">
                        <i class="bi bi-save"></i> Create Book
                    </button>
                </div>
            </form>
        </div>
        <div class="card-footer text-muted">
            <a asp-action="Index" class="btn btn-secondary">
                <i class="bi bi-arrow-left"></i> Back to List
            </a>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

IS_Project-master/IS_Project-master/EShop.Web/Views/Books/Delete.cshtml
@model EShop.Domain.Domain.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.yearOfRelease)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.yearOfRelease)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IS_Project-master/IS_Project-master/EShop.Web/Views/Books/Details.cshtml
@model EShop.Domain.Domain.Book

@{
    ViewData["Title"] = "Details";
}

<div class="container mt-4">
    <h1 class="mb-4">@ViewData["Title"]</h1>

    <div class="card shadow-lg">
        <div class="card-header bg-info text-white">
            <h4>Book Details</h4>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3">Title</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Title)</dd>

                <dt class="col-sm-3">Description</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Description)</dd>

                <dt class="col-sm-3">Year of Release</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.yearOfRelease)</dd>

                <dt class="col-sm-3">Author</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.AuthorId)</dd>

                <dt class="col-sm-3">Genre</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.genre)</dd>

                <dt class="col-sm-3">Price</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Price)</dd>

                <dt class="col-sm-3">Availability</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.IsAvailable)</dd>
            </dl>
        </div>
        <div class="card-footer">
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-warning">
                <i class="bi bi-pencil"></i> Edit
            </a>
            <a asp-action="Index" class="btn btn-secondary">
                <i class="bi bi-arrow-left"></i> Back to List
            </a>
        </div>
    </div>
</div>

IS_Project-master/IS_Project-master/EShop.Web/Views/Books/Edit.cshtml
@model EShop.Domain.Domain.Book

@{
    ViewData["Title"] = "Edit";
}

<div class="container mt-4">
    <h1 class="mb-4">@ViewData["Title"]</h1>

    <div class="card shadow-lg">
        <div class="card-header bg-warning text-white">
            <h4>Edit Book</h4>
        </div>
        <div class="card-body">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>

                <div class="mb-3">
                    <label asp-for="Title" class="form-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Description" class="form-label"></label>
                    <textarea asp-for="Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="yearOfRelease" class="form-label"></label>
                    <input asp-for="yearOfRelease" class="form-control" />
                    <span asp-validation-for="yearOfRelease" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="AuthorId" class="form-label"></label>
                    <input asp-for="AuthorId" class="form-control" />
                    <span asp-validation-for="AuthorId" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="genre" class="form-label"></label>
                    <input asp-for="genre" class="form-control" />
                    <span asp-validation-for="genre" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="Price" class="form-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label asp-for="IsAvailable" class="form-label"></label>
                    <input asp-for="IsAvailable" class="form-control" />
                    <span asp-validation-for="IsAvailable" class="text-danger"></span>
                </div>

                <input type="hidden" asp-for="Id" />

                <div class="d-grid mt-4">
                    <button type="submit" class="btn btn-primary btn-block">
                        <i class="bi bi-save"></i> Save Changes
                    </button>
                </div>
            </form>
        </div>
        <div class="card-footer text-muted">
            <a asp-action="Index" class="btn btn-secondary">
                <i class="bi bi-arrow-left"></i> Back to List
            </a>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

IS_Project-master/IS_Project-master/EShop.Web/Views/Books/Index.cshtml
@model IEnumerable<EShop.Domain.Domain.Book>

@{
    ViewData["Title"] = "Books";
}

<div class="container mt-4">
    <h1 class="mb-4">@ViewData["Title"]</h1>

    <p>
        <a asp-action="Create" class="btn btn-primary mb-4">Create New Book</a>
    </p>

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
        @foreach (var item in Model)
        {
            <div class="col">
                <div class="card h-100">
                    <img src="@item.BookImage" class="card-img-top" alt="@item.Title" style="max-height: 200px; object-fit: cover;" />
                    <div class="card-body">
                        <h5 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h5>
                        <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>
                        <p class="card-text">
                            <strong>Year of Release:</strong> @Html.DisplayFor(modelItem => item.yearOfRelease) <br />
                            <strong>Genre:</strong> @Html.DisplayFor(modelItem => item.genre) <br />
                            <strong>Price:</strong> @Html.DisplayFor(modelItem => item.Price) <br />
                            <strong>Available:</strong> @Html.DisplayFor(modelItem => item.IsAvailable)
                        </p>
                    </div>
                    <div class="card-footer">
                        <!-- First row: Edit, Delete, Details -->
                        <div class="row mb-2">
                            <div class="col">
                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning w-100">Edit</a>
                            </div>
                            <div class="col">
                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info text-white w-100">Details</a>
                            </div>
                            <div class="col">
                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger w-100">Delete</a>
                            </div>
                        </div>

                        <!-- Second row: Publish, Add to Cart -->
                        <div class="row">
                            <div class="col">
                                <a asp-action="Create" asp-controller="Publishers" asp-route-id="@item.Id" class="btn btn-primary w-100 @(item.IsAvailable.Value ? true : "disabled")">Publish</a>
                            </div>
                            <div class="col">
                                <a asp-controller="Books" asp-action="AddToCart" asp-route-id="@item.Id" class="btn btn-secondary w-100">Add to Cart</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>